//
// includes an extra table for instructions for 0xCB
//

static cpu_instruction ext_instructions[0x100] = {
	[0x00] = {INSTRUCT_CB_RLC, MODE_REG, REG_B},
	[0x01] = {INSTRUCT_CB_RLC, MODE_REG, REG_C},
	[0x02] = {INSTRUCT_CB_RLC, MODE_REG, REG_D},
	[0x03] = {INSTRUCT_CB_RLC, MODE_REG, REG_E},
	[0x04] = {INSTRUCT_CB_RLC, MODE_REG, REG_H},
	[0x05] = {INSTRUCT_CB_RLC, MODE_REG, REG_L},
	[0x06] = {INSTRUCT_CB_RLC, MODE_ADDR, REG_HL},
	[0x07] = {INSTRUCT_CB_RLC, MODE_REG, REG_A},
	[0x08] = {INSTRUCT_CB_RR, MODE_REG, REG_B},
	[0x09] = {INSTRUCT_CB_RR, MODE_REG, REG_C},
	[0x0A] = {INSTRUCT_CB_RR, MODE_REG, REG_D},
	[0x0B] = {INSTRUCT_CB_RR, MODE_REG, REG_E},
	[0x0C] = {INSTRUCT_CB_RR, MODE_REG, REG_H},
	[0x0D] = {INSTRUCT_CB_RR, MODE_REG, REG_L},
	[0x0E] = {INSTRUCT_CB_RR, MODE_ADDR, REG_HL},
	[0x0F] = {INSTRUCT_CB_RR, MODE_REG, REG_A},

	[0x10] = {INSTRUCT_CB_RL, MODE_REG, REG_B},
	[0x11] = {INSTRUCT_CB_RL, MODE_REG, REG_C},
	[0x12] = {INSTRUCT_CB_RL, MODE_REG, REG_D},
	[0x13] = {INSTRUCT_CB_RL, MODE_REG, REG_E},
	[0x14] = {INSTRUCT_CB_RL, MODE_REG, REG_H},
	[0x15] = {INSTRUCT_CB_RL, MODE_REG, REG_L},
	[0x16] = {INSTRUCT_CB_RL, MODE_ADDR, REG_HL},
	[0x17] = {INSTRUCT_CB_RL, MODE_REG, REG_A},
	[0x18] = {INSTRUCT_CB_RR, MODE_REG, REG_B},
	[0x19] = {INSTRUCT_CB_RR, MODE_REG, REG_C},
	[0x1A] = {INSTRUCT_CB_RR, MODE_REG, REG_D},
	[0x1B] = {INSTRUCT_CB_RR, MODE_REG, REG_E},
	[0x1C] = {INSTRUCT_CB_RR, MODE_REG, REG_H},
	[0x1D] = {INSTRUCT_CB_RR, MODE_REG, REG_L},
	[0x1E] = {INSTRUCT_CB_RR, MODE_ADDR, REG_HL},
	[0x1F] = {INSTRUCT_CB_RR, MODE_REG, REG_A},

	[0x20] = {INSTRUCT_CB_SLA, MODE_REG, REG_B},
	[0x21] = {INSTRUCT_CB_SLA, MODE_REG, REG_C},
	[0x22] = {INSTRUCT_CB_SLA, MODE_REG, REG_D},
	[0x23] = {INSTRUCT_CB_SLA, MODE_REG, REG_E},
	[0x24] = {INSTRUCT_CB_SLA, MODE_REG, REG_H},
	[0x25] = {INSTRUCT_CB_SLA, MODE_REG, REG_L},
	[0x26] = {INSTRUCT_CB_SLA, MODE_ADDR, REG_HL},
	[0x27] = {INSTRUCT_CB_SLA, MODE_REG, REG_A},
	[0x28] = {INSTRUCT_CB_SRA, MODE_REG, REG_B},
	[0x29] = {INSTRUCT_CB_SRA, MODE_REG, REG_C},
	[0x2A] = {INSTRUCT_CB_SRA, MODE_REG, REG_D},
	[0x2B] = {INSTRUCT_CB_SRA, MODE_REG, REG_E},
	[0x2C] = {INSTRUCT_CB_SRA, MODE_REG, REG_H},
	[0x2D] = {INSTRUCT_CB_SRA, MODE_REG, REG_L},
	[0x2E] = {INSTRUCT_CB_SRA, MODE_ADDR, REG_HL},
	[0x2F] = {INSTRUCT_CB_SRA, MODE_REG, REG_A},

	[0x30] = {INSTRUCT_CB_SWAP, MODE_REG, REG_B},
	[0x31] = {INSTRUCT_CB_SWAP, MODE_REG, REG_C},
	[0x32] = {INSTRUCT_CB_SWAP, MODE_REG, REG_D},
	[0x33] = {INSTRUCT_CB_SWAP, MODE_REG, REG_E},
	[0x34] = {INSTRUCT_CB_SWAP, MODE_REG, REG_H},
	[0x35] = {INSTRUCT_CB_SWAP, MODE_REG, REG_L},
	[0x36] = {INSTRUCT_CB_SWAP, MODE_ADDR, REG_HL},
	[0x37] = {INSTRUCT_CB_SWAP, MODE_REG, REG_A},
	[0x38] = {INSTRUCT_CB_SRL, MODE_REG, REG_B},
	[0x39] = {INSTRUCT_CB_SRL, MODE_REG, REG_C},
	[0x3A] = {INSTRUCT_CB_SRL, MODE_REG, REG_D},
	[0x3B] = {INSTRUCT_CB_SRL, MODE_REG, REG_E},
	[0x3C] = {INSTRUCT_CB_SRL, MODE_REG, REG_H},
	[0x3D] = {INSTRUCT_CB_SRL, MODE_REG, REG_L},
	[0x3E] = {INSTRUCT_CB_SRL, MODE_ADDR, REG_HL},
	[0x3F] = {INSTRUCT_CB_SRL, MODE_REG, REG_A},

	[0x40] = {INSTRUCT_CB_BIT, MODE_REG, REG_B, .parameter = 0},
	[0x41] = {INSTRUCT_CB_BIT, MODE_REG, REG_C, .parameter = 0},
	[0x42] = {INSTRUCT_CB_BIT, MODE_REG, REG_D, .parameter = 0},
	[0x43] = {INSTRUCT_CB_BIT, MODE_REG, REG_E, .parameter = 0},
	[0x44] = {INSTRUCT_CB_BIT, MODE_REG, REG_H, .parameter = 0},
	[0x45] = {INSTRUCT_CB_BIT, MODE_REG, REG_L, .parameter = 0},
	[0x46] = {INSTRUCT_CB_BIT, MODE_ADDR, REG_HL, REG_HL, .parameter = 0},
	[0x47] = {INSTRUCT_CB_BIT, MODE_REG, REG_A, .parameter = 0},
	[0x48] = {INSTRUCT_CB_BIT, MODE_REG, REG_B, .parameter = 1},
	[0x49] = {INSTRUCT_CB_BIT, MODE_REG, REG_C, .parameter = 1},
	[0x4A] = {INSTRUCT_CB_BIT, MODE_REG, REG_D, .parameter = 1},
	[0x4B] = {INSTRUCT_CB_BIT, MODE_REG, REG_E, .parameter = 1},
	[0x4C] = {INSTRUCT_CB_BIT, MODE_REG, REG_H, .parameter = 1},
	[0x4D] = {INSTRUCT_CB_BIT, MODE_REG, REG_L, .parameter = 1},
	[0x4E] = {INSTRUCT_CB_BIT, MODE_REG, REG_HL, REG_HL, .parameter = 1},
	[0x4F] = {INSTRUCT_CB_BIT, MODE_REG, REG_A, .parameter = 1},

	[0x50] = {INSTRUCT_CB_BIT, MODE_REG, REG_B, .parameter = 2},
	[0x51] = {INSTRUCT_CB_BIT, MODE_REG, REG_C, .parameter = 2},
	[0x52] = {INSTRUCT_CB_BIT, MODE_REG, REG_D, .parameter = 2},
	[0x53] = {INSTRUCT_CB_BIT, MODE_REG, REG_E, .parameter = 2},
	[0x54] = {INSTRUCT_CB_BIT, MODE_REG, REG_H, .parameter = 2},
	[0x55] = {INSTRUCT_CB_BIT, MODE_REG, REG_L, .parameter = 2},
	[0x56] = {INSTRUCT_CB_BIT, MODE_ADDR, REG_HL, REG_HL, .parameter = 2},
	[0x57] = {INSTRUCT_CB_BIT, MODE_REG, REG_A, .parameter = 2},
	[0x58] = {INSTRUCT_CB_BIT, MODE_REG, REG_B, .parameter = 3},
	[0x59] = {INSTRUCT_CB_BIT, MODE_REG, REG_C, .parameter = 3},
	[0x5A] = {INSTRUCT_CB_BIT, MODE_REG, REG_D, .parameter = 3},
	[0x5B] = {INSTRUCT_CB_BIT, MODE_REG, REG_E, .parameter = 3},
	[0x5C] = {INSTRUCT_CB_BIT, MODE_REG, REG_H, .parameter = 3},
	[0x5D] = {INSTRUCT_CB_BIT, MODE_REG, REG_L, .parameter = 3},
	[0x5E] = {INSTRUCT_CB_BIT, MODE_REG, REG_HL, REG_HL, .parameter = 3},
	[0x5F] = {INSTRUCT_CB_BIT, MODE_REG, REG_A, .parameter = 3},

	[0x60] = {INSTRUCT_CB_BIT, MODE_REG, REG_B, .parameter = 4},
	[0x61] = {INSTRUCT_CB_BIT, MODE_REG, REG_C, .parameter = 4},
	[0x62] = {INSTRUCT_CB_BIT, MODE_REG, REG_D, .parameter = 4},
	[0x63] = {INSTRUCT_CB_BIT, MODE_REG, REG_E, .parameter = 4},
	[0x64] = {INSTRUCT_CB_BIT, MODE_REG, REG_H, .parameter = 4},
	[0x65] = {INSTRUCT_CB_BIT, MODE_REG, REG_L, .parameter = 4},
	[0x66] = {INSTRUCT_CB_BIT, MODE_ADDR, REG_HL, REG_HL, .parameter = 4},
	[0x67] = {INSTRUCT_CB_BIT, MODE_REG, REG_A, .parameter = 4},
	[0x68] = {INSTRUCT_CB_BIT, MODE_REG, REG_B, .parameter = 5},
	[0x69] = {INSTRUCT_CB_BIT, MODE_REG, REG_C, .parameter = 5},
	[0x6A] = {INSTRUCT_CB_BIT, MODE_REG, REG_D, .parameter = 5},
	[0x6B] = {INSTRUCT_CB_BIT, MODE_REG, REG_E, .parameter = 5},
	[0x6C] = {INSTRUCT_CB_BIT, MODE_REG, REG_H, .parameter = 5},
	[0x6D] = {INSTRUCT_CB_BIT, MODE_REG, REG_L, .parameter = 5},
	[0x6E] = {INSTRUCT_CB_BIT, MODE_REG, REG_HL, REG_HL, .parameter = 5},
	[0x6F] = {INSTRUCT_CB_BIT, MODE_REG, REG_A, .parameter = 5},

	[0x70] = {INSTRUCT_CB_BIT, MODE_REG, REG_B, .parameter = 6},
	[0x71] = {INSTRUCT_CB_BIT, MODE_REG, REG_C, .parameter = 6},
	[0x72] = {INSTRUCT_CB_BIT, MODE_REG, REG_D, .parameter = 6},
	[0x73] = {INSTRUCT_CB_BIT, MODE_REG, REG_E, .parameter = 6},
	[0x74] = {INSTRUCT_CB_BIT, MODE_REG, REG_H, .parameter = 6},
	[0x75] = {INSTRUCT_CB_BIT, MODE_REG, REG_L, .parameter = 6},
	[0x76] = {INSTRUCT_CB_BIT, MODE_ADDR, REG_HL, REG_HL, .parameter = 6},
	[0x77] = {INSTRUCT_CB_BIT, MODE_REG, REG_A, .parameter = 6},
	[0x78] = {INSTRUCT_CB_BIT, MODE_REG, REG_B, .parameter = 7},
	[0x79] = {INSTRUCT_CB_BIT, MODE_REG, REG_C, .parameter = 7},
	[0x7A] = {INSTRUCT_CB_BIT, MODE_REG, REG_D, .parameter = 7},
	[0x7B] = {INSTRUCT_CB_BIT, MODE_REG, REG_E, .parameter = 7},
	[0x7C] = {INSTRUCT_CB_BIT, MODE_REG, REG_H, .parameter = 7},
	[0x7D] = {INSTRUCT_CB_BIT, MODE_REG, REG_L, .parameter = 7},
	[0x7E] = {INSTRUCT_CB_BIT, MODE_REG, REG_HL, REG_HL, .parameter = 7},
	[0x7F] = {INSTRUCT_CB_BIT, MODE_REG, REG_A, .parameter = 7},

	[0x80] = {INSTRUCT_CB_RES, MODE_REG, REG_B, .parameter = 0},
	[0x81] = {INSTRUCT_CB_RES, MODE_REG, REG_C, .parameter = 0},
	[0x82] = {INSTRUCT_CB_RES, MODE_REG, REG_D, .parameter = 0},
	[0x83] = {INSTRUCT_CB_RES, MODE_REG, REG_E, .parameter = 0},
	[0x84] = {INSTRUCT_CB_RES, MODE_REG, REG_H, .parameter = 0},
	[0x85] = {INSTRUCT_CB_RES, MODE_REG, REG_L, .parameter = 0},
	[0x86] = {INSTRUCT_CB_RES, MODE_ADDR, REG_HL, REG_HL, .parameter = 0},
	[0x87] = {INSTRUCT_CB_RES, MODE_REG, REG_A, .parameter = 0},
	[0x88] = {INSTRUCT_CB_RES, MODE_REG, REG_B, .parameter = 1},
	[0x89] = {INSTRUCT_CB_RES, MODE_REG, REG_C, .parameter = 1},
	[0x8A] = {INSTRUCT_CB_RES, MODE_REG, REG_D, .parameter = 1},
	[0x8B] = {INSTRUCT_CB_RES, MODE_REG, REG_E, .parameter = 1},
	[0x8C] = {INSTRUCT_CB_RES, MODE_REG, REG_H, .parameter = 1},
	[0x8D] = {INSTRUCT_CB_RES, MODE_REG, REG_L, .parameter = 1},
	[0x8E] = {INSTRUCT_CB_RES, MODE_REG, REG_HL, REG_HL, .parameter = 1},
	[0x8F] = {INSTRUCT_CB_RES, MODE_REG, REG_A, .parameter = 1},

	[0x90] = {INSTRUCT_CB_RES, MODE_REG, REG_B, .parameter = 2},
	[0x91] = {INSTRUCT_CB_RES, MODE_REG, REG_C, .parameter = 2},
	[0x92] = {INSTRUCT_CB_RES, MODE_REG, REG_D, .parameter = 2},
	[0x93] = {INSTRUCT_CB_RES, MODE_REG, REG_E, .parameter = 2},
	[0x94] = {INSTRUCT_CB_RES, MODE_REG, REG_H, .parameter = 2},
	[0x95] = {INSTRUCT_CB_RES, MODE_REG, REG_L, .parameter = 2},
	[0x96] = {INSTRUCT_CB_RES, MODE_ADDR, REG_HL, REG_HL, .parameter = 2},
	[0x97] = {INSTRUCT_CB_RES, MODE_REG, REG_A, .parameter = 2},
	[0x98] = {INSTRUCT_CB_RES, MODE_REG, REG_B, .parameter = 3},
	[0x99] = {INSTRUCT_CB_RES, MODE_REG, REG_C, .parameter = 3},
	[0x9A] = {INSTRUCT_CB_RES, MODE_REG, REG_D, .parameter = 3},
	[0x9B] = {INSTRUCT_CB_RES, MODE_REG, REG_E, .parameter = 3},
	[0x9C] = {INSTRUCT_CB_RES, MODE_REG, REG_H, .parameter = 3},
	[0x9D] = {INSTRUCT_CB_RES, MODE_REG, REG_L, .parameter = 3},
	[0x9E] = {INSTRUCT_CB_RES, MODE_REG, REG_HL, REG_HL, .parameter = 3},
	[0x9F] = {INSTRUCT_CB_RES, MODE_REG, REG_A, .parameter = 3},

	[0xA0] = {INSTRUCT_CB_RES, MODE_REG, REG_B, .parameter = 4},
	[0xA1] = {INSTRUCT_CB_RES, MODE_REG, REG_C, .parameter = 4},
	[0xA2] = {INSTRUCT_CB_RES, MODE_REG, REG_D, .parameter = 4},
	[0xA3] = {INSTRUCT_CB_RES, MODE_REG, REG_E, .parameter = 4},
	[0xA4] = {INSTRUCT_CB_RES, MODE_REG, REG_H, .parameter = 4},
	[0xA5] = {INSTRUCT_CB_RES, MODE_REG, REG_L, .parameter = 4},
	[0xA6] = {INSTRUCT_CB_RES, MODE_ADDR, REG_HL, REG_HL, .parameter = 4},
	[0xA7] = {INSTRUCT_CB_RES, MODE_REG, REG_A, .parameter = 4},
	[0xA8] = {INSTRUCT_CB_RES, MODE_REG, REG_B, .parameter = 5},
	[0xA9] = {INSTRUCT_CB_RES, MODE_REG, REG_C, .parameter = 5},
	[0xAA] = {INSTRUCT_CB_RES, MODE_REG, REG_D, .parameter = 5},
	[0xAB] = {INSTRUCT_CB_RES, MODE_REG, REG_E, .parameter = 5},
	[0xAC] = {INSTRUCT_CB_RES, MODE_REG, REG_H, .parameter = 5},
	[0xAD] = {INSTRUCT_CB_RES, MODE_REG, REG_L, .parameter = 5},
	[0xAE] = {INSTRUCT_CB_RES, MODE_REG, REG_HL, REG_HL, .parameter = 5},
	[0xAF] = {INSTRUCT_CB_RES, MODE_REG, REG_A, .parameter = 5},

	[0xB0] = {INSTRUCT_CB_RES, MODE_REG, REG_B, .parameter = 6},
	[0xB1] = {INSTRUCT_CB_RES, MODE_REG, REG_C, .parameter = 6},
	[0xB2] = {INSTRUCT_CB_RES, MODE_REG, REG_D, .parameter = 6},
	[0xB3] = {INSTRUCT_CB_RES, MODE_REG, REG_E, .parameter = 6},
	[0xB4] = {INSTRUCT_CB_RES, MODE_REG, REG_H, .parameter = 6},
	[0xB5] = {INSTRUCT_CB_RES, MODE_REG, REG_L, .parameter = 6},
	[0xB6] = {INSTRUCT_CB_RES, MODE_ADDR, REG_HL, REG_HL, .parameter = 6},
	[0xB7] = {INSTRUCT_CB_RES, MODE_REG, REG_A, .parameter = 6},
	[0xB8] = {INSTRUCT_CB_RES, MODE_REG, REG_B, .parameter = 7},
	[0xB9] = {INSTRUCT_CB_RES, MODE_REG, REG_C, .parameter = 7},
	[0xBA] = {INSTRUCT_CB_RES, MODE_REG, REG_D, .parameter = 7},
	[0xBB] = {INSTRUCT_CB_RES, MODE_REG, REG_E, .parameter = 7},
	[0xBC] = {INSTRUCT_CB_RES, MODE_REG, REG_H, .parameter = 7},
	[0xBD] = {INSTRUCT_CB_RES, MODE_REG, REG_L, .parameter = 7},
	[0xBE] = {INSTRUCT_CB_RES, MODE_REG, REG_HL, REG_HL, .parameter = 7},
	[0xBF] = {INSTRUCT_CB_RES, MODE_REG, REG_A, .parameter = 7},

	[0xC0] = {INSTRUCT_CB_SET, MODE_REG, REG_B, .parameter = 0},
	[0xC1] = {INSTRUCT_CB_SET, MODE_REG, REG_C, .parameter = 0},
	[0xC2] = {INSTRUCT_CB_SET, MODE_REG, REG_D, .parameter = 0},
	[0xC3] = {INSTRUCT_CB_SET, MODE_REG, REG_E, .parameter = 0},
	[0xC4] = {INSTRUCT_CB_SET, MODE_REG, REG_H, .parameter = 0},
	[0xC5] = {INSTRUCT_CB_SET, MODE_REG, REG_L, .parameter = 0},
	[0xC6] = {INSTRUCT_CB_SET, MODE_ADDR, REG_HL, REG_HL, .parameter = 0},
	[0xC7] = {INSTRUCT_CB_SET, MODE_REG, REG_A, .parameter = 0},
	[0xC8] = {INSTRUCT_CB_SET, MODE_REG, REG_B, .parameter = 1},
	[0xC9] = {INSTRUCT_CB_SET, MODE_REG, REG_C, .parameter = 1},
	[0xCA] = {INSTRUCT_CB_SET, MODE_REG, REG_D, .parameter = 1},
	[0xCB] = {INSTRUCT_CB_SET, MODE_REG, REG_E, .parameter = 1},
	[0xCC] = {INSTRUCT_CB_SET, MODE_REG, REG_H, .parameter = 1},
	[0xCD] = {INSTRUCT_CB_SET, MODE_REG, REG_L, .parameter = 1},
	[0xCE] = {INSTRUCT_CB_SET, MODE_REG, REG_HL, REG_HL, .parameter = 1},
	[0xCF] = {INSTRUCT_CB_SET, MODE_REG, REG_A, .parameter = 1},

	[0xD0] = {INSTRUCT_CB_SET, MODE_REG, REG_B, .parameter = 2},
	[0xD1] = {INSTRUCT_CB_SET, MODE_REG, REG_C, .parameter = 2},
	[0xD2] = {INSTRUCT_CB_SET, MODE_REG, REG_D, .parameter = 2},
	[0xD3] = {INSTRUCT_CB_SET, MODE_REG, REG_E, .parameter = 2},
	[0xD4] = {INSTRUCT_CB_SET, MODE_REG, REG_H, .parameter = 2},
	[0xD5] = {INSTRUCT_CB_SET, MODE_REG, REG_L, .parameter = 2},
	[0xD6] = {INSTRUCT_CB_SET, MODE_ADDR, REG_HL, REG_HL, .parameter = 2},
	[0xD7] = {INSTRUCT_CB_SET, MODE_REG, REG_A, .parameter = 2},
	[0xD8] = {INSTRUCT_CB_SET, MODE_REG, REG_B, .parameter = 3},
	[0xD9] = {INSTRUCT_CB_SET, MODE_REG, REG_C, .parameter = 3},
	[0xDA] = {INSTRUCT_CB_SET, MODE_REG, REG_D, .parameter = 3},
	[0xDB] = {INSTRUCT_CB_SET, MODE_REG, REG_E, .parameter = 3},
	[0xDC] = {INSTRUCT_CB_SET, MODE_REG, REG_H, .parameter = 3},
	[0xDD] = {INSTRUCT_CB_SET, MODE_REG, REG_L, .parameter = 3},
	[0xDE] = {INSTRUCT_CB_SET, MODE_REG, REG_HL, REG_HL, .parameter = 3},
	[0xDF] = {INSTRUCT_CB_SET, MODE_REG, REG_A, .parameter = 3},

	[0xE0] = {INSTRUCT_CB_SET, MODE_REG, REG_B, .parameter = 4},
	[0xE1] = {INSTRUCT_CB_SET, MODE_REG, REG_C, .parameter = 4},
	[0xE2] = {INSTRUCT_CB_SET, MODE_REG, REG_D, .parameter = 4},
	[0xE3] = {INSTRUCT_CB_SET, MODE_REG, REG_E, .parameter = 4},
	[0xE4] = {INSTRUCT_CB_SET, MODE_REG, REG_H, .parameter = 4},
	[0xE5] = {INSTRUCT_CB_SET, MODE_REG, REG_L, .parameter = 4},
	[0xE6] = {INSTRUCT_CB_SET, MODE_ADDR, REG_HL, REG_HL, .parameter = 4},
	[0xE7] = {INSTRUCT_CB_SET, MODE_REG, REG_A, .parameter = 4},
	[0xE8] = {INSTRUCT_CB_SET, MODE_REG, REG_B, .parameter = 5},
	[0xE9] = {INSTRUCT_CB_SET, MODE_REG, REG_C, .parameter = 5},
	[0xEA] = {INSTRUCT_CB_SET, MODE_REG, REG_D, .parameter = 5},
	[0xEB] = {INSTRUCT_CB_SET, MODE_REG, REG_E, .parameter = 5},
	[0xEC] = {INSTRUCT_CB_SET, MODE_REG, REG_H, .parameter = 5},
	[0xED] = {INSTRUCT_CB_SET, MODE_REG, REG_L, .parameter = 5},
	[0xEE] = {INSTRUCT_CB_SET, MODE_REG, REG_HL, REG_HL, .parameter = 5},
	[0xEF] = {INSTRUCT_CB_SET, MODE_REG, REG_A, .parameter = 5},

	[0xF0] = {INSTRUCT_CB_SET, MODE_REG, REG_B, .parameter = 6},
	[0xF1] = {INSTRUCT_CB_SET, MODE_REG, REG_C, .parameter = 6},
	[0xF2] = {INSTRUCT_CB_SET, MODE_REG, REG_D, .parameter = 6},
	[0xF3] = {INSTRUCT_CB_SET, MODE_REG, REG_E, .parameter = 6},
	[0xF4] = {INSTRUCT_CB_SET, MODE_REG, REG_H, .parameter = 6},
	[0xF5] = {INSTRUCT_CB_SET, MODE_REG, REG_L, .parameter = 6},
	[0xF6] = {INSTRUCT_CB_SET, MODE_ADDR, REG_HL, REG_HL, .parameter = 6},
	[0xF7] = {INSTRUCT_CB_SET, MODE_REG, REG_A, .parameter = 6},
	[0xF8] = {INSTRUCT_CB_SET, MODE_REG, REG_B, .parameter = 7},
	[0xF9] = {INSTRUCT_CB_SET, MODE_REG, REG_C, .parameter = 7},
	[0xFA] = {INSTRUCT_CB_SET, MODE_REG, REG_D, .parameter = 7},
	[0xFB] = {INSTRUCT_CB_SET, MODE_REG, REG_E, .parameter = 7},
	[0xFC] = {INSTRUCT_CB_SET, MODE_REG, REG_H, .parameter = 7},
	[0xFD] = {INSTRUCT_CB_SET, MODE_REG, REG_L, .parameter = 7},
	[0xFE] = {INSTRUCT_CB_SET, MODE_REG, REG_HL, REG_HL, .parameter = 7},
	[0xFF] = {INSTRUCT_CB_SET, MODE_REG, REG_A, .parameter = 7},
};
